function plot_init_BmbSmbC(md, name)
%PLOT_INITN_ Plot and save initial fields
%
% Usage:
%   plot_initn_(md)
%   plot_initn_(md, 'my_figure')

% Default filename
if nargin < 2
    name = 'init_field';
end

% Create figure (non-interactive)
fig = figure('Visible','off');

plotmodel(md, ...
    'figure', fig, ...
    'nlines', 1, 'ncols', 3, ...
    'data', md.smb.mass_balance, ...
    'title', 'SMB mass balance', ...
    'colorbar', 'on', ...
    'colorbartitle', 'm/yr', ...
    'data', md.friction.coefficient, ...
    'title', 'Friction coefficient', ...
    'colorbar', 'on', ...
    'data', md.basalforcings.floatingice_melting_rate, ...
    'title', 'Floating ice melt rate', ...
    'caxis', [-3 0], ...
    'colormap', melt_colormap_white_to_blue(), ...
    'colorbar', 'on', ...
    'colorbartitle', 'm/yr');

% Create output directory if needed
if ~exist('./Figs','dir')
    mkdir('./Figs');
end

% Output path
outfile = ['./Fig/' name '.jpeg'];

% Save figure
print(fig, outfile, '-djpeg', '-r300');

fprintf('Saved figure: %s\n', outfile);

% Close figure
close(fig);

end


function cmap = melt_colormap_white_to_blue()

n = 256;

cmap = [ ...
    linspace(0,1,n)', ...
    linspace(0.2,1,n)', ...
    linspace(1,1,n)' ...
];

end
